export const travelerLanguages = [
  "English",
  "Spanish",
  "French",
  "German",
  "Portuguese",
  "Italian",
  "Japanese",
  "Korean",
  "Chinese (Simplified)",
  "Arabic",
  "Hindi",
  "Dutch",
  "Swedish",
];

export const localLanguages = [
  "Thai",
  "Japanese",
  "Korean",
  "Vietnamese",
  "Indonesian",
  "Malay",
  "Mandarin Chinese",
  "Cantonese",
  "Spanish",
  "French",
  "Italian",
  "Portuguese",
  "German",
  "Greek",
  "Turkish",
  "Arabic",
  "Hindi",
  "Czech",
  "Polish",
  "Hungarian",
];

export const businessTypes = [
  { value: "restaurant", label: "Restaurant / cafe" },
  { value: "hotel", label: "Hotel / guesthouse" },
  { value: "pharmacy", label: "Pharmacy" },
  { value: "clinic", label: "Clinic / dentist" },
  { value: "shop", label: "Shop / market stall" },
  { value: "tour", label: "Tour desk / activity" },
  { value: "transport", label: "Taxi / transfer / rental" },
  { value: "salon", label: "Salon / spa" },
  { value: "other", label: "Other local business" },
];
